name: Shell Commands

on:
  push:
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Echo String
        run: echo "Hello world"

      - name: Check Node.js and npm Versions
        run: |
          node -v
          npm -v
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"] #Which means that the above job will run first before the python job below. 
    steps:
      - name: Directory
        run: |
          echo "Present working directory:"
          cd
          pwd
      
      step: 
      - name: Directory in Bash
        run: |
          echo "Present working directory (Bash):"
          pwd
        shell: bash
