name: Terraform

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Terraform Init 
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan and Apply
        run: terraform apply -auto-approve


   #THIS IS TO SETUP TERRAFORM IN YOUR LOCAL ENVIRONMENT