name: Shell Commands

on:
  push:
    branches:
      - main 

jobs:
  run-shell-command:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 
        
      - name: Echo String
        run: echo "Hello world" 

      - name: Check Node.js and npm Versions
        run: |
          node -v
          npm -v
